language: cpp
sudo: false
dist: trusty

os: linux
addons:
  apt:
    sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-trusty-7"]
    packages: ["g++-7", "llvm-7-dev"]

before_script:
- set -e
- export CXX=g++-7
- mkdir build
- cd build

matrix:
  include:
  - name: "LLVM"
    script: cmake ..                                -DLINK_WITH_LLVM=YES
  - name: "Coverage"
    script: cmake .. -DCMAKE_CXX_FLAGS="--coverage -Wl,-lgcov"
  - name: "LLVM + Coverage"
    script: cmake .. -DCMAKE_CXX_FLAGS="--coverage -Wl,-lgcov" -DLINK_WITH_LLVM=YES

after_script:
- make VERBOSE=1
- ./Test
- ldd ./Test
- nm -S CMakeFiles/Test.dir/main.cpp.o | grep _GLOBAL__sub_D_00100_1__Z7runTestv
- nm -S CMakeFiles/Test.dir/main.cpp.o | grep __gcov_exit
- nm -S /usr/lib/llvm-7/lib/libLLVMCore.a | grep __gcov_exit
- nm -S /usr/lib/llvm-7/lib/libLLVMBinaryFormat.a | grep __gcov_exit
- nm -S /usr/lib/llvm-7/lib/libLLVMSupport.a | grep __gcov_exit
- nm -S /usr/lib/llvm-7/lib/libLLVMDemangle.a | grep __gcov_exit
