language: cpp
sudo: false
dist: trusty

matrix:
  include:
  - os: linux
    compiler: gcc
    addons:
      apt:
        sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-trusty-7"]
        packages: ["g++-7", "llvm-7-dev"]
    script:
    - export CXX=g++-7
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug ..
    - make VERBOSE=1
    - test/suite
  - os: linux
    compiler: gcc
    addons:
      apt:
        sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-trusty-7"]
        packages: ["g++-7", "llvm-7-dev"]
 #   install:
 #   - pip install --user cpp-coveralls
    script:
    - export CXX=g++-7
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug -DTEST_COVERAGE=YES ..
    - make VERBOSE=1
    - test/suite
 #   after_success:
 #   - coveralls --gcov gcov-7 --gcov-options '\-lp' --root ${TRAVIS_BUILD_DIR} --build-root ${TRAVIS_BUILD_DIR}/build -e Examples -e test -e CLI --extension cpp --extension hpp -i src -i include