language: cpp
sudo: false
dist: trusty

os: linux
addons:
  apt:
    sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-trusty-7"]
    packages: ["g++-7", "llvm-7-dev"]

before_script:
- set -e
- export CXX=g++-7
- mkdir build
- cd build

matrix:
  include:
  - name: "LLVM"
    script: cmake ..                                -DLINK_WITH_LLVM=YES
  - name: "Coverage"
    script: cmake .. -DCMAKE_CXX_FLAGS="--coverage -Wl,-lgcov"
  - name: "LLVM + Coverage"
    script: cmake .. -DCMAKE_CXX_FLAGS="--coverage -Wl,-lgcov" -DLINK_WITH_LLVM=YES

after_script:
- make VERBOSE=1
- ./Test
- ldd ./Test
